### ISSUE TITLE
Polyfill enter vr bug

### ISSUE THREAD

**Issue by HalfdanJ** [googlevr/webvr-ui#1]
There is an issue using polyfill the way we use the `vrdisplaypresentchange` event. We assume the event to by of type [VRDisplayEvent](https://w3c.github.io/webvr/#vrdisplayevent), but in polyfill its not, and the display property is not set. 

https://github.com/googlevr/webvr-ui/blob/master/src/webvr-manager.js#L210

@borismus Is this something that could be added to polyfill, or should we make a workaround for polyfill?

**Comment by HalfdanJ** [comment]
Oh looking closer, display is supplied, but under detail: https://github.com/googlevr/webvr-polyfill/blob/93253c78bcffc22ae263cb9aba361c3c172d16e6/src/base.js#L335  Is this an old spec syntax?

**Comment by borismus** [comment]
Yes, IIRC the only field a custom event can provide is 'detail'... So we
can't change the polyfill in this regard. I guess this should be more
clearly documented.

**Comment by HalfdanJ** [comment]
Aha, okay thanks. Then we'll make this workaround.

**Comment by borismus** [comment]
Thanks! Let me know when I can update from NPM.

**Comment by HalfdanJ** [comment]
Updated, and released on npm
