### ISSUE TITLE
A-Frame Can't Enter Fullscreen with Compatible Browser

### ISSUE THREAD

**Issue by evanaubrey** [googlevr/webvr-ui#12]
I see that with the Basic WebVR example there is a link to go full screen if there is no headset detected. Why can't I implement that same function within an A-Frame scene?

**Comment by HalfdanJ** [comment]
There shouldn't be anything hindering you from calling the requestEnterFullscreen function using a button, like in the basic example: https://github.com/googlevr/webvr-ui/blob/master/examples/basic.html#L96

If this doesn't work with A-Frame, feel free to re-open the issue.
